name: Check Jeep Page

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute
  workflow_dispatch:

jobs:
  check_page:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache Python Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache Firefox and Geckodriver
        uses: actions/cache@v4
        with:
          path: |
            /opt/firefox
            /usr/local/bin/geckodriver
          key: ${{ runner.os }}-firefox-geckodriver-${{ hashFiles('**/check_page.yml') }}
          restore-keys: |
            ${{ runner.os }}-firefox-geckodriver-

      - name: Install Dependencies
        run: |
          set -ex
          python -m pip install --upgrade pip selenium
          sudo apt update
          sudo snap remove firefox || true
          sudo snap remove geckodriver || true
          sudo apt-get purge firefox -y || true
          sudo rm -f /snap/bin/geckodriver
          sudo apt install -y wget curl xvfb jq libgtk-3-0 libxtst6 libx11-xcb1 libdbus-glib-1-2
      
          if [ ! -d "/opt/firefox" ]; then
            wget -O firefox.tar.xz "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US"
            sudo tar -xJf firefox.tar.xz -C /opt/
          fi
          sudo ln -sf /opt/firefox/firefox /usr/bin/firefox
      
          if [ ! -f "/usr/local/bin/geckodriver" ]; then
            GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r '.tag_name')
            wget -O geckodriver.tar.gz "https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz"
            sudo tar -xzf geckodriver.tar.gz -C /usr/local/bin/
            sudo chmod +x /usr/local/bin/geckodriver
          fi

      - name: Run Python script
        run: |
          Xvfb :99 -screen 0 1024x768x24 &
          export DISPLAY=:99
          sleep 3
          python check_jeep_page.py

      - name: Upload Logs if Exists
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 404-logs
          path: 404/*.txt
