name: Check Jeep Page

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  check_page:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip selenium
          sudo apt update
          sudo snap remove firefox || true
          sudo apt-get purge firefox -y || true
          sudo apt install -y firefox wget xvfb
          GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r .tag_name)
          wget "https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz"
          sudo tar -xzf geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz -C /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver

      - name: Run Python script
        run: |
          Xvfb :99 -screen 0 1024x768x24 &
          export DISPLAY=:99
          sleep 3
          python check_jeep_page.py

      - name: Upload Logs if Exists
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 404-logs
          path: 404/*.txt
