name: Check Jeep Page

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  check_page:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          sudo apt-get update
          sudo apt-get install -y firefox xvfb wget curl
          GECKODRIVER_VERSION=$(curl --silent "https://api.github.com/repos/mozilla/geckodriver/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          wget https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz
          sudo tar -xzf geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz -C /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver

      - name: Run Python Script
        run: |
          mkdir -p 404
          Xvfb :99 -screen 0 1024x768x24 &
          export DISPLAY=:99
          sleep 3
          python check_jeep_page.py

      - name: Upload Logs (if exist)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 404-logs
          path: 404/*.txt
          if-no-files-found: ignore
